language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.1

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git -b dev-7 # Clone pillar
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf

deploy:
	provider: releases
  api_key:
    secure: aqE5qPyTMKbklg+io867S2cgRYBqHA30/+GnIkPj7je7bRrhmXqi+NVuZRp0TXxhhVdSanQrdGOtza/4PbTwqz15NbiLLk6aJ5jeOHRGwLhyGIUqv/JDU/rgzc+4t0H7A070ARgZ3aIaCAj3g3Iq/ph8FrfU4+jHXuzsrlwVzQz15xZWUVB7tn6wCh6JCj6jYXJKpjDc8n1NJWHcF19bOBvol7qUWbLdfkUgW78rcDS9bTugro7REaDCA3WTtB1njc3diD52NJrM1QsLa/FQo0i3eWdHpF3ZHNiEHSV4tBReXXanaWpVU/Lcvg0dAgbtyn1oda2XajBPLtp4MvxNBb8MlfsUqoyBd6fgXw1hjRDUGM2a/FBNqenB5aOcxXiduEE1/3WTmdMkKtQk+SiaOec9QGmfY26553yZAc2/XPW5ImB05t5OmBFD04JRnmwO3R7wOHw6N+tVEpAIrYjabiG+6zl7igrCNR9WLJ4PecMc5LCL7uHQGCun6trzDLK3v29CBQVqgK81Hlbqm+A3E0ajwoEaqInhuip1HrU4sIjL+XJG2g0XEjgIZBs5GcdTemQr0mwvUcNXn8yVEnL2II8bLt/pLLlIT68jOOk4LPx4iKROgzkY8ZCaPnhdB2w1mRzdOI0Ct3ObXdaAKIcgbvBqfNJydLosvEjykTuJ/t8=
  file: build/book.spiral.pdf
  skip_cleanup: true
  on:
	repo: cormas/Booklet-CORMAS
	tags: true
